baseURL = "https://davidissamattos.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "David's public blog"
theme = "hugo-bearblog"
enableEmoji = true
enableRobotsTXT = true

[params]
  author = "David Issa Mattos"
  description = "I am a data scientist and researcher with interest in music, music information retrieval, statistics, AI, causal inference and automotive data analysis."
  
  # Social links (bearblog uses these in footer)
  email = "issamattos.david@gmail.com"
  hideMadeWithLine = true
  # Copyright notice
  copyright = "2020-2025"

# Menu items
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2

  [[menu.main]]
    name = "Music"
    url = "/music/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
